# Generated by Django 4.2.5 on 2023-09-28 14:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0004_listingdetails_date_added_bids"),
    ]

    operations = [
        migrations.AddField(
            model_name="bids",
            name="num_of_bids",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="listingdetails",
            name="date_added",
            field=models.DateField(blank=True),
        ),
    ]
