# Generated by Django 4.2.5 on 2023-09-29 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0005_bids_num_of_bids_alter_listingdetails_date_added"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="added_by",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="watchlist",
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
