# Generated by Django 4.2.5 on 2023-09-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0006_listing_added_by_user_watchlist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="watchlist",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
