# Generated by Django 4.2.5 on 2023-09-29 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0008_alter_user_watchlist"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="watchlist",
        ),
        migrations.AddField(
            model_name="listing",
            name="watchlist",
            field=models.ManyToManyField(
                related_name="multiple_reference", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="added_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="single_reference",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
