# Generated by Django 4.2.5 on 2023-10-04 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0010_listing_active_alter_listing_watchlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="won_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="won_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
