# Generated by Django 4.2.5 on 2023-10-05 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0011_listing_won_by_alter_listing_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="listingdetails",
            name="comments",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="listingdetails",
            name="img",
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
